 type: google.api.Service
 config_version: 3

 http:
   rules:
   - selector: service.Documents.Get
     get: /v1/document/{identifier}
   - selector: service.Documents.Store
     put: /v1/document/{document.identifier}
     body: document.content
